name: Publish to RubyGems

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Publish Gem
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Build gem
        run: |
          gem build nng.gemspec
          echo "GEM_FILE=$(ls nng-ruby-*.gem)" >> $GITHUB_ENV

      - name: Publish to RubyGems
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          mkdir -p ~/.gem
          cat > ~/.gem/credentials << EOF
          ---
          :rubygems_api_key: ${GEM_HOST_API_KEY}
          EOF
          chmod 0600 ~/.gem/credentials
          gem push ${{ env.GEM_FILE }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.GEM_FILE }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
